config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  namespace :administration do
  	get '/', to: 'posts#index'
    resources :posts
    resources :podcasts
    post 'posts/generate_internal_link', to: 'posts#generate_internal_link'
    resources :categories
    resources :resources
    resources :comments
    post '/approve_comment/:id', to: 'comments#approve_comment', as: :approve_comment
    delete '/remove_comment/:id', to: 'comments#remove_comment', as: :remove_comment
    post '/reply_comment', to: 'comments#reply_comment', as: :reply_comment
  end

  constraints subdomain: 'm' do
    get '/blog', to: 'posts#mobile_index', as: :blog_mobile
    get '/services', to: 'home#services', as: :services_mobile
    get '/resources', to: 'resources#index', as: :mobile_resources
    get '/resources/filter_by/:category', to: 'resources#filter_by', as: :mobile_filter_resources
    root to: 'home#mobile_index'
    get ':slug', to: 'posts#mobile_show'
  end

  post '/subscribe', to: 'subscriptions#create', as: :subscribe
  resource :contact do
    post 'send', to: 'contact#send_message', as: :send
  end

  get '/filter_by_category/:category', to: 'posts#filter_by_category', as: :filter_by_category
  post '/home/load_info', to: 'home#load_info'
  post '/post/likes', to: 'posts#new_like'
  post '/post/social-stats', to: 'posts#social_stats'
  resources :comments
  get 'feed', to: 'posts#feed', :defaults => { :format => "xml" }
  get 'podcast_feed', to: 'podcasts#feed', :defaults => { :format => "xml" }
  get '/blog', to: 'posts#index', as: :blog
  get '/services', to: 'home#services'
  get '/resources', to: 'resources#index'
  get '/resources/filter_by/:category', to: 'resources#filter_by', as: :filter_resources
  get '/resources/download/:id', to: 'resources#increment_stats'
  post '/resources/likes', to: 'resources#new_like'
  get '/sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }
  root to: 'home#index'
  get ':slug', to: 'posts#show', as: 'show_post'
end

app/views/layouts/shared/_analytics.html.erb
<script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 ga('create', '<%= ENV['ANALYTICS_CODE'] %>', '<%= ENV['ANALYTICS_SITE'] %>');
 ga('send', 'pageview');

</script>

app/views/layouts/shared/_cookies_alert.html.haml
#cookies-alert.cookies-alert
  .content
    .col-md-10
      Esta web utiliza cookies para mejorar su experiencia. Si continúa navegando consideramos que acepta el
      %a{ 'data-toggle':"modal", 'data-target': "#main-modal", rel: 'no-follow' }
        uso de cookies.
    .col-md-2
      %button{ id: 'accept-cookies-btn'}
        Acepto

%script
  new CookiesHandler();

app/views/layouts/shared/_cookies_policy.html.haml
.modal-text
  %h3
    What Are Cookies
  %p
    As is common practice with almost all professional websites this site uses cookies, which are tiny files that are downloaded to your computer, to improve your experience. This page describes what information they gather, how we use it and why we sometimes need to store these cookies. We will also share how you can prevent these cookies from being stored however this may downgrade or 'break' certain elements of the sites functionality.
  %p
    For more general information on cookies see the Wikipedia article on HTTP Cookies...
  %h3
    How We Use Cookies
  %p
    We use cookies for a variety of reasons detailed below. Unfortunately in most cases there are no industry standard options for disabling cookies without completely disabling the functionality and features they add to this site. It is recommended that you leave on all cookies if you are not sure whether you need them or not in case they are used to provide a service that you use.
  %h3
    Disabling Cookies
  %p
    You can prevent the setting of cookies by adjusting the settings on your browser (see your browser Help for how to do this). Be aware that disabling cookies will affect the functionality of this and many other websites that you visit. Disabling cookies will usually result in also disabling certain functionality and features of the this site. Therefore it is recommended that you do not disable cookies.
  %h3
  The Cookies We Set
  %p
    If you create an account with us then we will use cookies for the management of the signup process and general administration. These cookies will usually be deleted when you log out however in some cases they may remain afterwards to remember your site preferences when logged out.
  %p
    This site offers newsletter or email subscription services and cookies may be used to remember if you are already registered and whether to show certain notifications which might only be valid to subscribed/unsubscribed users. 
  %p
    In order to provide you with a great experience on this site we provide the functionality to set your preferences for how this site runs when you use it. In order to remember your preferences we need to set cookies so that this information can be called whenever you interact with a page is affected by your preferences.
  %h3
    Third Party Cookies
  %p
    In some special cases we also use cookies provided by trusted third parties. The following section details which third party cookies you might encounter through this site.
  %p
    This site uses Google Analytics which is one of the most widespread and trusted analytics solution on the web for helping us to understand how you use the site and ways that we can improve your experience. These cookies may track things such as how long you spend on the site and the pages that you visit so we can continue to produce engaging content.
  %p
    For more information on Google Analytics cookies, see the official Google Analytics page.
  %p
    Third party analytics are used to track and measure usage of this site so that we can continue to produce engaging content. These cookies may track things such as how long you spend on the site or pages you visit which helps us to understand how we can improve the site for you.
  %p
    From time to time we test new features and make subtle changes to the way that the site is delivered. When we are still testing new features these cookies may be used to ensure that you receive a consistent experience whilst on the site whilst ensuring we understand which optimisations our users appreciate the most.
  %p
    In some cases we may provide you with custom content based on what you tell us about yourself either directly or indirectly by linking a social media account. These types of cookies simply allow us to provide you with content that we feel may be of interest to you.
  %p
    We also use social media buttons and/or plugins on this site that allow you to connect with your social network in various ways. For these to work the following social media sites including; Twitter, Facebook, Google+, LinkedIn, will set cookies through our site which may be used to enhance your profile on their site or contribute to the data they hold for various purposes outlined in their respective privacy policies.
  %h3
    More Information
  %p
    Hopefully that has clarified things for you and as was previously mentioned if there is something that you aren't sure whether you need or not it's usually safer to leave cookies enabled in case it does interact with one of the features you use on our site. However if you are still looking for more information then you can contact us through one of our preferred contact methods.
  %p
    Email: 
    %a{ href: 'mailto:patricia@patriciacarmona.com', target: '_blank' } 
      patricia@patriciacarmona.com
%p.center
  %button.close-modal.dark.big.close-modal{ 'data-dismiss': "modal"}
    Ok

app/views/layouts/shared/_footer.html.haml
.footer
  .container
    %ul{ class: 'list-inline' }
      %li
        %a{ rel: "license", href: "http://creativecommons.org/licenses/by-sa/4.0/", rel: 'no-follow' }
          = image_tag(image_path('cc_bysa.png'), style:"border-width:0", alt:' Licencia Creative Commons', height: 31, width: 88)
      %li
        = "-"
      %li
        %a{ 'data-toggle':"modal", 'data-target': "#main-modal", rel: 'no-follow' }
          Política de cookies
      %li
        = "-"
      %li
        = link_to "Contacto", '/services#contact-me'
      %li.right
        = link_to 'http://feedly.com/i/subscription/feed/http://patriciacarmona.com/feed/', rel: 'no-follow', target: '_blank', title: 'Sígueme en Feedly', class: 'footer-link' do
          %i.fa.feedly.fa-2x
      %li.right
        = link_to 'https://ie.linkedin.com/in/carmonapulidopatricia/en', rel: 'no-follow', target: '_blank', title: 'Sígueme en LinkedIn' do
          %i.fa.fa-linkedin.linkedin.fa-2x
      %li.right
        = link_to 'http://twitter.com/patricrp', rel: 'no-follow', target: '_blank', title: 'Sígueme en Twitter' do
          %i.fa.fa-twitter.twitter.fa-2x

app/views/layouts/shared/_main_modal.html.haml
#main-modal.modal.fade.modal-cookies{ tabindex: 1, role: 'dialog', 'arial-labelledby': 'main-modal', 'aria-hidden': true }
  .modal-dialog.modal-md
    .modal-exit
      %button.close-modal{ 'data-dismiss': "modal"}
        X
    .modal-content
      

app/views/layouts/shared/_main_navbar.html.haml
#navbar{ class: "navbar navbar-default navbar-static-top #{ @post.nil? ? 'home-navbar' : nil }"}
  .container
    %button{ type:"button", class: "navbar-toggle", 'data-toggle':"collapse", 'data-target':".navbar-responsive-collapse" }
    %a.navbar-brand{ href:"/" }
      Patricia Carmona
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav.right
        %li
          = link_to "Blog", blog_path
        %li
          = link_to "Recursos", resources_path
        %li
          = link_to "Sobre mí", "/services#about-me"
        %li
          = link_to "Servicios", "/services"
        %li
          = link_to "Contacto", "/services#contact-me"

app/views/layouts/shared/_metas_blog.html.haml
%meta{ name: 'author', content: 'Patricia Carmona' }
%meta{ name: 'publisher', content: 'Patricia Carmona' }
%meta{ name: 'description', content: 'Patricia Carmona, analista de social media. Hablo sobre Social Media y Marketing. Puedes encontrar noticias, cursos, informes y recursos. ¡Únete a mi comunidad!' }
%meta{ name: 'keywords', content: 'social media, marketing, cursos, informes, recursos, blog, campañas, redes sociales' }

%meta{ property: 'og:title', content: 'Patricia Carmona | Análisis Social Media' }
%meta{ property: 'og:type', content: 'blog' }
%meta{ property: 'og:url', content: 'http://www.patriciacarmona.com' }
%meta{ property: 'og:image', content: header_meta_image(image_path('author.jpg')) }
%meta{ property: 'og:site_name', content: 'Patricia Carmona' }
%meta{ property: 'og:description', content: 'Patricia Carmona, analista de social media. Hablo sobre Social Media y Marketing. Puedes encontrar noticias, cursos, informes y recursos. ¡Únete a mi comunidad!' }

%meta{ name: 'twitter:card', content: 'summary_large_image' }
%meta{ name: 'twitter:site', content: '@patricrp' }
%meta{ name: 'twitter:domain', content: 'www.patriciacarmona.com' }
%meta{ name: 'twitter:title', content: 'Patricia Carmona | Análisis Social Media' }
%meta{ name: 'twitter:description', content: 'Patricia Carmona, analista de social media. Hablo sobre Social Media y Marketing. Puedes encontrar noticias, cursos, informes y recursos. ¡Únete a mi comunidad!' }
%meta{ name: 'twitter:image', content: header_meta_image(image_path('author.jpg')) }

%meta{ property: 'fb:admins', content: '1567942686751387'}
%link{rel:"canonical", href:"http://www.patriciacarmona.com/"}

app/views/layouts/shared/_metas_post.html.haml
%meta{ name: 'author', content: "#{content_for?(:author) ? yield(:author) : nil}" }
%meta{ name: 'publisher', content: "#{content_for?(:author) ? yield(:author) : nil}"  }
%meta{ name: 'description', content: "#{content_for?(:resume) ? yield(:resume) : nil}"  }
%meta{ name: 'keywords', content: "#{content_for?(:category) ? yield(:category) : nil}"  }

%meta{ property: 'og:title', content: "Patricia Carmona | #{content_for?(:title) ? yield(:title) : nil}" }
%meta{ property: 'og:type', content: 'post' }
%meta{ property: 'og:url', content: "http://www.patriciacarmona.com/#{@post.slug}" }
%meta{ property: 'og:image', content: header_meta_image(content_for?(:image) ? yield(:image) : image_path('author.jpg')) }
%meta{ property: 'og:site_name', content: 'Patricia Carmona' }
%meta{ property: 'og:description', content: "#{content_for?(:resume) ? yield(:resume) : nil}" }

%meta{ name: 'twitter:card', content: 'summary_large_image' }
%meta{ name: 'twitter:site', content: '@patricrp' }
%meta{ name: 'twitter:domain', content: 'www.patriciacarmona.com' }
%meta{ name: 'twitter:title', content: "#{content_for?(:title) ? yield(:title) : nil}" }
%meta{ name: 'twitter:description', content: "#{content_for?(:resume) ? yield(:resume) : nil}" }
%meta{ name: 'twitter:image', content: header_meta_image(content_for?(:image) ? yield(:image) : image_path('author.jpg')) }

%meta{ property: 'fb:admins', content: '1567942686751387'}
%link{rel:"canonical", href:"http://www.patriciacarmona.com/#{content_for?(:slug) ? yield(:slug) : nil}"}
%meta{name: "robots", content:"noodp" }

app/views/layouts/shared/_mobile_main_navbar.html.haml
%i.fa.fa-bars.fa-3x.menu-buttonOpen{ onclick: 'openSideMenu();'}
.header-socialNetworks
  = link_to 'http://feedly.com/i/subscription/feed/http://patriciacarmona.com/feed/', rel: 'no-follow', target: '_blank', title: 'Sígueme en Feedly' do
    %i.fa.feedly.fa-2x

#side-navbar{ class: "side-navbar"}
  .container
    .side-navbarHeader
      = image_tag(image_path('author.jpg'))
      %h2.side-navbarHeaderTitle
        Patricia Carmona
    %ul.nav
      %li
        = link_to "Inicio", root_path()
      %li
        = link_to "Blog", blog_mobile_path()
      %li
        = link_to "Recursos", resources_path
      %li
        = link_to "Sobre mí", "/services#about-me"
      %li
        = link_to "Servicios", "/services"
      %li.button
        = link_to "Contacto", "/services#contact-me"