config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  namespace :administration do
  	get '/', to: 'posts#index'
    resources :posts
    resources :podcasts
    post 'posts/generate_internal_link', to: 'posts#generate_internal_link'
    resources :categories
    resources :resources
    resources :comments
    post '/approve_comment/:id', to: 'comments#approve_comment', as: :approve_comment
    delete '/remove_comment/:id', to: 'comments#remove_comment', as: :remove_comment
    post '/reply_comment', to: 'comments#reply_comment', as: :reply_comment
  end

  constraints subdomain: 'm' do
    get '/blog', to: 'posts#mobile_index', as: :blog_mobile
    get '/services', to: 'home#services', as: :services_mobile
    get '/resources', to: 'resources#index', as: :mobile_resources
    get '/resources/filter_by/:category', to: 'resources#filter_by', as: :mobile_filter_resources
    root to: 'home#mobile_index'
    get ':slug', to: 'posts#mobile_show'
  end

  post '/subscribe', to: 'subscriptions#create', as: :subscribe
  resource :contact do
    post 'send', to: 'contact#send_message', as: :send
  end

  get '/filter_by_category/:category', to: 'posts#filter_by_category', as: :filter_by_category
  post '/home/load_info', to: 'home#load_info'
  post '/post/likes', to: 'posts#new_like'
  post '/post/social-stats', to: 'posts#social_stats'
  resources :comments
  get 'feed', to: 'posts#feed', :defaults => { :format => "xml" }
  get 'podcast_feed', to: 'podcasts#feed', :defaults => { :format => "xml" }
  get '/blog', to: 'posts#index', as: :blog
  get '/services', to: 'home#services'
  get '/resources', to: 'resources#index'
  get '/resources/filter_by/:category', to: 'resources#filter_by', as: :filter_resources
  get '/resources/download/:id', to: 'resources#increment_stats'
  post '/resources/likes', to: 'resources#new_like'
  get '/sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }
  root to: 'home#index'
  get ':slug', to: 'posts#show', as: 'show_post'
end

app/controllers/administration/categories_controller.rb
module Administration
  # Controller for admin  categories
  class CategoriesController < AdministrationController
    def index
      @categories = Category.all
    end

    def show
      @category = Category.find(params[:id])
    end

    def new
      @category ||= Category.new
    end

    def edit
      @category ||= Category.find(params[:id])
    end

    def create
      @category = Category.new(category_params)
      if @category.valid?
        @category.save
        redirect_to administration_categories_path
      else
        redirect_to action: 'new'
      end
    end

    def update
      category = Category.find(params[:id])
      if category.update_attributes(category_params)
        redirect_to administration_categories_path
      else
        redirect_to edit_administration_category_path(category.id)
      end
    end

    def destroy
      category ||= Category.find(params[:id])
      if category.destroy
        flash[:notice] = 'The category was removed successful.'
      else
        flash[:error] = 'The category wasn´t removed successful. Please, try again in a few minutes.'
      end
      redirect_to administration_categories_path
    end

    private

    def category_params
      params.require(:category).permit(:name, :description)
    end
  end
end

app/controllers/administration/comments_controller.rb
class Administration::CommentsController < ApplicationController
  layout 'administration'
  
  def index
    @pending_comments = Comment.pending
    @approved_comments = Comment.original.approved
  end

  def approve_comment
    comment = Comment.find params[:id]
    if comment.update_attribute(:status, true)
      flash[:notice]= 'El comentario fue aprobado con éxito.'
    else
      flash[:error]= 'Ha pasado algo mientras se aprobaba el comentario. Pregunta a Juan.'
    end
    redirect_to administration_comments_path
  end

  def remove_comment
    comment = Comment.find params[:id]
    if comment.delete
      flash[:notice]= 'El comentario fue eliminado con éxito.'
    else
      flash[:error]= 'Ha pasado algo mientras se eliminaba el comentario. Pregunta a Juan.'
    end
    redirect_to administration_comments_path
  end

  def reply_comment
    reply = Comment.new(comment_params)
    if reply.valid?
      reply.save
      flash[:notice] = "Respuesta publicada con éxito."
    else
      flash[:error] = "Error al guardar la respuesta. Habla con Juan."
    end
    redirect_to administration_comments_path
  end

  private

  def comment_params
    comment_params = params.require(:comment).permit(:name, :email, :content, :post_id, :reply_to_id)
    comment_params[:name] = "Patricia Carmona"
    comment_params[:email] = "patricia@patriciacarmona.com"
    comment_params[:status] = true
    comment_params
  end
end

app/controllers/administration/podcasts_controller.rb
class Administration::PodcastsController < ApplicationController
  layout 'administration'

  def index
    @podcasts = Podcast.all.order(:created_at)
  end

  def new
    @podcast = Podcast.new
  end

  def create
    @podcast = Podcast.new(podcast_params)
    if @podcast.valid?
      @podcast.save
      redirect_to administration_podcasts_path
    else
      redirect_to action: 'new'
    end
  end

  private

  def podcast_params
    params.require(:podcast).permit(:title, :description, :file, :external_links)
    params[:podcast][:external_links] = params[:podcast][:external_links].permit!.to_h
    params[:podcast].permit!
  end
end

app/controllers/administration/posts_controller.rb
module Administration
  # Controller for admin  posts
  class PostsController < AdministrationController
    before_action :check_user

    before_action only: [:create, :update] do
      expire_fragment("home_blog_info") if fragment_exist?("home_blog_info")
    end

    layout 'administration', only: [:new, :edit]

    def index
      @posts = Post.all.order(published: :desc)
    end

    def show
      @post ||= Post.find(params[:id])
      @shares = StatData.shares_post(@post.id)
      render layout: 'admin_post'
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)
      if @post.valid?
        @post.save
        redirect_to administration_post_path(id: @post.id)
      else
        render template: 'administration/posts/new'
      end
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      post = Post.find(params[:id])
      if post.update_attributes!(post_params)
        flash[:notice] = 'The post was updated successful.'
        redirect_to administration_posts_path
      else
        flash[:error] = 'Detected errors in the form. Please, review and fix them.'
        redirect_to edit_administration_post_path(id: post.id)
      end
    end

    def destroy
      post = Post.find(params[:id])
      if post.destroy
        flash[:notice] = 'The post was deleted successful!'
      else
        flash[:error] = "The post couldn't be deleted. Please, try again."
      end
      redirect_to administration_posts_path
    end

    def generate_internal_link
      render json: Post.generate_internal_link(params[:title])
    end

    private

    def post_params
      post = if params["post"]["image"].is_a?(ActionDispatch::Http::UploadedFile)
               params.require(:post).permit(:content, :title, :published, :resume, :author, :tags, :category, :external_link, :image, :resource_id, :podcast_id)
             else
               params.require(:post).permit(:content, :title, :published, :resume, :author, :tags, :category, :external_link, :resource_id, :podcast_id)
             end
      post['published'] = build_published_date(params)
      post['category'] = Category.find params['post']['category'] if params['post']['category']
      post['content'] = save_images(post['content'], post['title'])
      remove_published_data(post)
    end

    def build_published_date(params)
      Time.parse("#{params['post']['published(1i)']}-"\
                 "#{params['post']['published(2i)']}-"\
                 "#{params['post']['published(3i)']}"\
                 " #{params['post']['published(4i)']}:"\
                 "#{params['post']['published(5i)']}")
      .in_time_zone
    end

    def remove_published_data(post)
      post.delete('published(1i)')
      post.delete('published(2i)')
      post.delete('published(3i)')
      post.delete('published(4i)')
      post.delete('published(5i)')
      post
    end

    def save_images(post_content, title)
      image_handler = ImageHandler.new(post_content, title)
      image_handler.parse
      image_handler.content
    end
  end
end

app/controllers/administration/resources_controller.rb
class Administration::ResourcesController < AdministrationController
  layout 'administration'

  before_action only: [:create, :update] do
    expire_fragment("resources_info") if fragment_exist?("resources_info")
  end

  def index
  	@resources = Resource.order(published: :desc)
  end

  def show
  	@resource = Resource.find(params[:id])
  end

  def edit
  	@resource = Resource.find(params[:id])
  end

  def new
    @resource = Resource.new
  end

  def create
    @resource = Resource.new(resource_params)
    if @resource.valid?
    	@resource.save
    	redirect_to administration_resource_path(id: @resource.id)
    else
    	render template: 'administration/resources/new'
    end
  end

  def update
    resource = Resource.find(params[:id])
    if resource.update_attributes(resource_params)
      flash[:notice] = 'The resource was updated successful.'
      redirect_to administration_resources_path
    else
      flash[:error] = 'Detected errors in the form. Please, review and fix them.'
      redirect_to edit_administration_resources_path(id: post.id)
    end
  end

  def destroy
    resource = Resource.find(params[:id])
    if resource.destroy
      flash[:notice] = 'The resource was deleted successful!'
    else
      flash[:error] = "The resource couldn't be deleted. Please, try again."
    end
    redirect_to administration_resources_path
  end

  private

  def resource_params
    if params["resource"]["image"].is_a?(ActionDispatch::Http::UploadedFile)
      params.require(:resource).permit(:title, :description, :link, :image, :category, :status, :published)
    else
      params.require(:resource).permit(:title, :description, :link, :category, :status, :published)
    end
  end
end

app/controllers/administration_controller.rb
# Administration class controller
class AdministrationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :current_section

  private

  def check_user
    @user = true if user_logged || exist_user
    if @user
      set_cookies_session
    else
      render file: "#{Rails.root}/public/404", layout: false, status: :not_found
    end
  end

  def set_cookies_session
    cookies.signed[:username] = true
    cookies.signed[:session_expired] = Time.zone.now + 30.minutes
    cookies.signed[:httponly] = true
  end

  def user_logged
    cookies.signed[:username].present? &&
      cookies.signed[:session_expired] &&
      cookies.signed[:session_expired] >= Time.zone.now
  end

  def exist_user
    params['user'] == ENV['CREDENTIALS']
  end

  def current_section
    @section = params[:controller].split('/').last
  end
end

app/helpers/administration/comments_helper.rb
module Administration::CommentsHelper
end

app/helpers/administration/resources_helper.rb
module Administration::ResourcesHelper
	def resources_categories
    ['Informes', 'Infografías', 'Plantillas']
  end
end

app/views/administration/resources/_form.html.haml
= simple_form_for [:administration, resource], html: { id: 'clear-form' } do |f|
  .form-group
    = f.input :title, input_html: { class: 'form-control' }, as: :string
  .form-group
    = f.input :description, input_html: { class: 'form-control', maxlength: 300}, as: :text
  .form-group
    = f.input :image, input_html: { class: 'form-control'}, as: :file
    - if resource.image?
      .info
        = "Usando: #{resource.image.url}"
  .form-group
    = f.input :link, input_html: { class: 'form-control col-md-4' }, as: :string
  .form-group
    = f.input :published, as: :datetime, order: [:day, :month, :year, :hour, :minute]
  .form-group
    = f.label :category, 'Categoria'
    %br
    = collection_radio_buttons(:resource, :category, resources_categories, :to_s, :to_s)
  .form-group
    = f.submit 'Finalizar', class: 'btn btn-lg btn-primary submit-btn'
    = link_to 'Cancel', administration_resources_path(), class: 'btn btn-lg btn-danger cancel-btn'

app/views/administration/resources/_list_resources.html.haml
- if resources.present?
  %table{ class: 'table'}
    %thead
      %tr
        %th{ class: 'col-md-5' }
          Title
        %th{ class: 'col-md-3' }
          Publish date
        %th{ class: 'col-md-1' }
          Downloads
        %th{ class: 'col-md-1' }
          Likes
        %th{ class: 'col-md-2' }
          Actions
    %tbody
      - resources.each do |resource|
        %tr
          %td
            = resource.title
          %td
            = resource.published
          %td
            = resource.downloads.to_i
          %td
            = resource.likes
          %td
            %ul{ class: 'list-inline' }
              %li
                =link_to edit_administration_resource_path(id: resource.id) do
                  %i{ class: 'fa fa-pencil fa-2x' }
              %li
                =link_to administration_resource_path(id: resource.id) do
                  %i{ class: 'fa fa-eye fa-2x' }
              %li
                =link_to administration_resource_path(id: resource.id), method: 'DELETE', data: { confirm: 'Are you sure?' } do
                  %i{ class: 'fa fa-trash fa-2x' }
- else
  %p
    No resources

app/views/administration/resources/edit.html.haml
= render partial: 'form', locals: { resource: @resource }

app/views/administration/resources/index.html.haml
= link_to new_administration_resource_path(), class: 'btn btn-primary right' do
  %i{ class: 'fa fa-plus' }
  = t('new_resource')
%h3
  Recursos
= render partial: 'administration/resources/list_resources', locals: { resources: @resources }

app/views/administration/resources/new.html.haml
= render partial: 'form', locals: { resource: @resource }

app/views/administration/resources/show.html.haml
%div{ id: "resource_#{@resource.id}", class: 'resource' }
  .row
    .col-md-4.resource-image
      - if @resource.image.url
        = image_tag(image_path(@resource.image.url))
    .col-md-8
      %h2.resource-title
        = @resource.title
      %p
        = @resource.description
      = link_to @resource.link, target: '_blank' do
        %i.fa.fa-download
        Descargar
%div{ class: 'actions' }
  = link_to administration_resources_path, class: 'btn btn-default btn-lg left' do
    %i{ class: 'fa fa-chevron-left'}
    = t('return')
  = link_to edit_administration_resource_path(id: @resource.id), class: 'btn btn-success btn-lg right' do
    %i{ class: 'fa fa-pencil'}
    = t('edit')