config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  namespace :administration do
  	get '/', to: 'posts#index'
    resources :posts
    resources :podcasts
    post 'posts/generate_internal_link', to: 'posts#generate_internal_link'
    resources :categories
    resources :resources
    resources :comments
    post '/approve_comment/:id', to: 'comments#approve_comment', as: :approve_comment
    delete '/remove_comment/:id', to: 'comments#remove_comment', as: :remove_comment
    post '/reply_comment', to: 'comments#reply_comment', as: :reply_comment
  end

  constraints subdomain: 'm' do
    get '/blog', to: 'posts#mobile_index', as: :blog_mobile
    get '/services', to: 'home#services', as: :services_mobile
    get '/resources', to: 'resources#index', as: :mobile_resources
    get '/resources/filter_by/:category', to: 'resources#filter_by', as: :mobile_filter_resources
    root to: 'home#mobile_index'
    get ':slug', to: 'posts#mobile_show'
  end

  post '/subscribe', to: 'subscriptions#create', as: :subscribe
  resource :contact do
    post 'send', to: 'contact#send_message', as: :send
  end

  get '/filter_by_category/:category', to: 'posts#filter_by_category', as: :filter_by_category
  post '/home/load_info', to: 'home#load_info'
  post '/post/likes', to: 'posts#new_like'
  post '/post/social-stats', to: 'posts#social_stats'
  resources :comments
  get 'feed', to: 'posts#feed', :defaults => { :format => "xml" }
  get 'podcast_feed', to: 'podcasts#feed', :defaults => { :format => "xml" }
  get '/blog', to: 'posts#index', as: :blog
  get '/services', to: 'home#services'
  get '/resources', to: 'resources#index'
  get '/resources/filter_by/:category', to: 'resources#filter_by', as: :filter_resources
  get '/resources/download/:id', to: 'resources#increment_stats'
  post '/resources/likes', to: 'resources#new_like'
  get '/sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }
  root to: 'home#index'
  get ':slug', to: 'posts#show', as: 'show_post'
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  include Mailchimp

  def create
    begin
      subscribe_user(subscription_list, subscriber_params)
      create_subscription_cookie
      template = 'subscriptions/confirmation'
    rescue Exception => e
      p "Error!"
      template = 'subscriptions/error'
    end

    respond_to do |format|
      format.js { render template: template, layout: false }
    end
  end

  private

  def subscriber_params
  	{
  	  body: {
  	  	email_address: params['subscription']['email'],
  	  	status: 'subscribed',
  	  	merge_fields: {
  	  	  'FNAME': params['subscription']['name']
  	  	}
  	  }
  	}
  end

  def subscription_list
    ENV['MAILCHIMP_SUBSCRIPTION_LIST_ID']
  end

  def create_subscription_cookie
    cookies[:subscribed] = {
      value: true,
      expires: 1.year.from_now,
      httponly: true
    }
  end

end

app/views/subscriptions/_already_exist.html.haml
.confirmation
  %h2
    ¡Ya estás suscrito a mi comunidad!
  %p
    Si quieres puedes seguirme también en
    = link_to 'http://twitter.com/patricrp', rel: 'no-follow', target: '_blank' do
      %i.fa.fa-twitter.twitter

app/views/subscriptions/_confirmation.html.haml
.confirmation
  %h2
    ¡Gracias por unirte a mi comunidad!
  %p
    Si quieres puedes seguirme también en
    = link_to 'http://twitter.com/patricrp', rel: 'no-follow', target: '_blank' do
      %i.fa.fa-twitter.twitter

app/views/subscriptions/_form.html.haml
%h3.title
  ¿Quieres recibir mis artículos directamente en tu correo?
= form_for 'subscription', url: subscribe_path, remote: true, html: { class: :form } do |f|
  .col-md-2.col-xs-12
    = f.text_field :name, placeholder: 'Nombre', class: 'form-control', required: true
  .col-md-8.col-xs-12
    = f.text_field :email, placeholder: 'Email', class: 'form-control', required: true
  .col-md-2.col-xs-12
    = f.submit 'Suscribirme', class:"btn btn-primary"

app/views/subscriptions/confirmation.js.haml
$('.subscription').html("#{ j render partial: 'subscriptions/confirmation.html' }")

app/views/subscriptions/error.js.haml
$('.subscription').html("#{ j render partial: 'subscriptions/already_exist.html' }")