config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  namespace :administration do
  	get '/', to: 'posts#index'
    resources :posts
    resources :podcasts
    post 'posts/generate_internal_link', to: 'posts#generate_internal_link'
    resources :categories
    resources :resources
    resources :comments
    post '/approve_comment/:id', to: 'comments#approve_comment', as: :approve_comment
    delete '/remove_comment/:id', to: 'comments#remove_comment', as: :remove_comment
    post '/reply_comment', to: 'comments#reply_comment', as: :reply_comment
  end

  constraints subdomain: 'm' do
    get '/blog', to: 'posts#mobile_index', as: :blog_mobile
    get '/services', to: 'home#services', as: :services_mobile
    get '/resources', to: 'resources#index', as: :mobile_resources
    get '/resources/filter_by/:category', to: 'resources#filter_by', as: :mobile_filter_resources
    root to: 'home#mobile_index'
    get ':slug', to: 'posts#mobile_show'
  end

  post '/subscribe', to: 'subscriptions#create', as: :subscribe
  resource :contact do
    post 'send', to: 'contact#send_message', as: :send
  end

  get '/filter_by_category/:category', to: 'posts#filter_by_category', as: :filter_by_category
  post '/home/load_info', to: 'home#load_info'
  post '/post/likes', to: 'posts#new_like'
  post '/post/social-stats', to: 'posts#social_stats'
  resources :comments
  get 'feed', to: 'posts#feed', :defaults => { :format => "xml" }
  get 'podcast_feed', to: 'podcasts#feed', :defaults => { :format => "xml" }
  get '/blog', to: 'posts#index', as: :blog
  get '/services', to: 'home#services'
  get '/resources', to: 'resources#index'
  get '/resources/filter_by/:category', to: 'resources#filter_by', as: :filter_resources
  get '/resources/download/:id', to: 'resources#increment_stats'
  post '/resources/likes', to: 'resources#new_like'
  get '/sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }
  root to: 'home#index'
  get ':slug', to: 'posts#show', as: 'show_post'
end

app/views/resources/_header.html.haml
.resources-header
  .col-md-8.col-xs-12
    %h2.resources-headerTitle
      Recursos
    .lead.resources-headerLead
      %p
        %i
          "Un recurso es un medio que sirve para conseguir lo que se pretende."
      %p
        En esta sección tienes a tu disposición un conjunto de infografías, plantillas, informes y documentación que puedes descargar de forma gratuita y te ayudarán a desarrollar tu trabajo de análisis, planificación y ejecución.
  .col-md-4.hidden-xs
    .creativity

app/views/resources/_list.html.haml
- resources.each do |resource|
  .row
    = render resource
- if category === nil
  .pagination
    = paginate resources

app/views/resources/_navigation.html.haml
.resources-nav
  %ul.nav.nav-tabs
    %li{role:"presentation", class: (!active ? 'active': nil) }
      = link_to "Todos", filter_resources_path('all'), remote: true
    - categories.each do |category|
      %li{role: 'presentation', class: (active == category ? 'active' : '') }
        = link_to category.camelcase, filter_resources_path(category), remote: true

app/views/resources/_resource.html.haml
.resource
  .col-md-4.hidden-xs
    .resource-image
      -if resource.image.url
        = image_tag(image_path(resource.image.thumb.url))
  .col-md-8.col-xs-12
    %h2.resource-title
      = resource.title
    %span.resource-date.right
      %i.fa.fa-calendar
      = "Publicado en #{resource.published.strftime('%d %b %Y')}"
    .resource-category
      %span
        =resource.category.camelcase
    .resource-description
      = resource.description
    .resource-link
      %ul.list-inline
        %li
          = link_to resource.link, onclick: 'downloadResource(event)', "data-ref": resource.id, target: '_blank' do
            %i.fa.fa-download.fa-2x
            %span.hidden-xs
              Descargar
        %li.likes.right{ "data-ref": resource.id }
          - if user_likes?(resource.link)
            %i.fa.fa-heart.fa-2x
          - else
            %i.fa.fa-heart-o.fa-2x
          %button
            = resource.likes

app/views/resources/filter_by.js.haml
$('#resources_list').html("#{ j render partial: 'resources/list', locals: { resources: resources, category: category } }")

$('#resources_nav').html("#{ j render partial: 'resources/navigation', locals: { categories: categories, active: category } }")

app/views/resources/index.html.haml
.row
  = render partial: 'layouts/shared/main_navbar'
.row
  #resources
    .container
      .row
        = render partial: 'header'
      .row#resources_nav
        = render partial: 'navigation', locals: { categories: @categories, active: nil }
      .row#resources_list
        = render partial: 'list', locals: { resources: @resources , category: nil}
.row
  = render partial: 'layouts/shared/footer'

app/views/resources/mobile_index.html.haml
.row
  #resources
    .container
      .row
        = render partial: 'header'
      .row-fluid#resources_nav
        = render partial: 'navigation', locals: { categories: @categories, active: nil }
      .row-fluid#resources_list
        = render partial: 'list', locals: { resources: @resources , category: nil}